app = ""
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  source="mysql_data" # name of the repo
  destination="/data"

[env]
  MYSQL_DATABASE = ""
  MYSQL_USER = ""

[build]
  image = "mysql:8"

[processes]
  app = "--datadir /data/mysql --default-authentication-plugin mysql_native_password --performance-schema=OFF --innodb-buffer-pool-size 64M"
